# Generated by Django 5.1 on 2024-08-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('BookContent', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=500)),
                ('books', models.ManyToManyField(to='books.bookmodel')),
            ],
        ),
    ]
