# Generated by Django 5.1 on 2024-08-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='BookContent',
            field=models.TextField(),
        ),
    ]
