# Generated by Django 5.1 on 2024-08-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookmodel_bookcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='BookContent',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='bookContent',
            field=models.FileField(default='', upload_to='BookContent'),
        ),
    ]
