# Generated by Django 5.1 on 2024-08-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookmodel_bookcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='bookContent',
            field=models.FileField(upload_to='Book'),
        ),
    ]
