# Generated by Django 5.1 on 2024-08-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookmodel_author_alter_bookmodel_bookcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
